/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type ExecuteMsg = {
  managed_status_changed_hook: ManagedStatusChangedHookMsg;
} | {
  add_managed_contract: {
    contract_address: Addr;
    contract_type: AssetTypes;
    [k: string]: unknown;
  };
} | {
  group_admin_hooks: {
    group_admin_hooks_msg: ExecuteMsg1;
    [k: string]: unknown;
  };
} | {
  update_fees: {
    add?: ManagementFee[] | null;
    remove?: number[] | null;
    [k: string]: unknown;
  };
} | {
  add_players_to_team: {
    players: PlayerInfo[];
    [k: string]: unknown;
  };
} | {
  create_new_asset: {
    asset_type: AssetTypes;
    user: Addr;
    [k: string]: unknown;
  };
};
export type ManagedStatus = "pending" | "enabled" | "disabled" | "suspended";
export type Addr = string;
export type AssetTypes = "Team" | "League" | "Display" | "App";
export type ExecuteMsg1 = {
  remove_hook: {
    addr: string;
    [k: string]: unknown;
  };
} | {
  add_hook: {
    addr: string;
    [k: string]: unknown;
  };
} | {
  update_admin: {
    admin_addr?: string | null;
    [k: string]: unknown;
  };
} | {
  update_members: {
    add: Member[];
    remove: string[];
    [k: string]: unknown;
  };
};
export type FeeType = "Dev" | "ServiceProvider";
export type Decimal = string;
export type Positions = "r_b" | "q_b" | "w_r1" | "w_r2" | "c_o" | "g_l" | "g_r" | "s" | "c_b1" | "c_b2" | "l_b" | "c_d" | "t_r" | "t_l";
export interface ManagedStatusChangedHookMsg {
  change: ManagedStatusUpdate;
  [k: string]: unknown;
}
export interface ManagedStatusUpdate {
  managed_contract: string;
  managed_status: ManagedStatus;
  manager_contract: string;
  [k: string]: unknown;
}
export interface Member {
  addr: string;
  weight: number;
}
export interface ManagementFee {
  active: boolean;
  created_at_block_height: number;
  fees: Fee;
  id: number;
  [k: string]: unknown;
}
export interface Fee {
  description?: string | null;
  fee_type: FeeType;
  percent: Decimal;
  to_address: Addr;
  [k: string]: unknown;
}
export interface PlayerInfo {
  address: Addr;
  assigned_team_address?: Addr | null;
  first_name: string;
  last_name: string;
  position: Positions;
  [k: string]: unknown;
}
export interface InstantiateMsg {
  admin: string;
  members: Member[];
  owner: Addr;
  teams?: {
    [k: string]: Addr[];
  } | null;
  teams_for_sale?: Addr[] | null;
  [k: string]: unknown;
}
export type QueryMsg = {
  get_management_info: {
    [k: string]: unknown;
  };
} | {
  get_managed_contract: {
    contract: Addr;
    [k: string]: unknown;
  };
};
export interface State {
  displays?: Addr[] | null;
  displays_for_sale?: Addr[] | null;
  leagues?: Addr[] | null;
  leagues_for_sale?: Addr[] | null;
  owner: Addr;
  players?: Addr[] | null;
  players_info?: PlayerInfo[] | null;
  teams?: Addr[] | null;
  teams_for_sale?: Addr[] | null;
  [k: string]: unknown;
}