/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient } from "@cosmjs/cosmwasm-stargate";
import { Addr, Positions, InfoResponse, Player, PlayerAttributes, AttrItem, InstantiateMsg, QueryMsg } from "./Player.types";
export interface PlayerReadOnlyInterface {
  contractAddress: string;
  getInfo: () => Promise<GetInfoResponse>;
}
export class PlayerQueryClient implements PlayerReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.getInfo = this.getInfo.bind(this);
  }

  getInfo = async (): Promise<GetInfoResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_info: {}
    });
  };
}