/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Addr = string;
export type Positions = "r_b" | "q_b" | "w_r1" | "w_r2" | "c_o" | "g_l" | "g_r" | "s" | "c_b1" | "c_b2" | "l_b" | "c_d" | "t_r" | "t_l";
export interface InfoResponse {
  player: Player;
  [k: string]: unknown;
}
export interface Player {
  attributes: PlayerAttributes;
  first_name: string;
  last_name: string;
  owner: Addr;
  position: Positions;
  [k: string]: unknown;
}
export interface PlayerAttributes {
  accuracy: AttrItem;
  agility: AttrItem;
  angle_of_view: number;
  football_iq: AttrItem;
  hands: AttrItem;
  leader: AttrItem;
  pressure_threshold: AttrItem;
  speed: AttrItem;
  strength: AttrItem;
  temperament: AttrItem;
  [k: string]: unknown;
}
export interface AttrItem {
  value: string;
  [k: string]: unknown;
}
export interface InstantiateMsg {
  attributes: PlayerAttributes;
  first_name: string;
  last_name: string;
  managing_contract_address: Addr;
  position: Positions;
  [k: string]: unknown;
}
export type QueryMsg = {
  get_info: {
    [k: string]: unknown;
  };
};